### PR TITLE
:bug: missed desc

### LINKED ISSUE #50: ConcurrentHashMap 实现原理
ConcurrentHashMap 实现原理还是要备注下版本吧，jdk8实现方式就发生变化了。

### PR DESCRIPTION
**Pull request by crossoverJie**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**The description of the PR:**
fixed #50 

**Other information:**

### CODE REVIEW

**Comment by 009647726089959** [comment]
Sent from Mail for Windows 10

**Comment by 009647726089959** [comment]
Sent from Mail for Windows 10

**Comment by 009647726089959** [comment]
Sent from Mail for Windows 10

**Comment by crossoverJie** [comment]
@009647726089959 what?

**Pull request merged**
